/// Catches any throws and switches if to af failure after printing the error.
public func printError(error: Error) {
    switch error {
    case Error.Error(let error):
        print("ðŸ’£ Error from service: \(error)")
    case Error.ErrorNS(let nserror):
        print("ðŸ’£ Error from service: \(nserror)")
    case Error.General:
        print("ðŸ’£ General service error")
    case Error.InvalidResponseData(_):
        print("ðŸ¤” Invalid response data")
    case Error.InvalidAuthentication:
        print("ðŸ’£ Invalid authentication")
    case Error.ShouldOverride:
        print("ðŸ’£ You should override this method")
    default:
        print("ðŸ’£ failed with unknown error \(error)")

    }
}